using System;

namespace Clean.Core.Application.Exceptions
{ 
    /// <summary>
    /// This class represent a  exception that is generated by do not found element in Persistence Repository
    /// </summary>
    public class NotFoundException : ApplicationException
    {
        /// <summary>
        /// Create a new NotFoundException
        /// </summary>
        /// <param name="name">Object name</param>
        /// <param name="key">Object key</param>
        public NotFoundException(string name, object key)
            : base($"{name} ({key}) not found")
        {
        }
    }
}
